### ISSUE TITLE
Support latest EAP

### ISSUE THREAD

**Issue by LoremFooBar** [unlocomqx/intellij-virtual-kit#1]
This plugin is a lifesaver when working on Sveltekit projects, thank you for making it! 
Is it possible to update it to support the latest 2024.1 EAP?

**Comment by unlocomqx** [comment]
Hi @LoremFooBar 

I published a new version, it will be available in 2 days after validation from the jetbrains team

I will try to publish the zip to github in the meanwhile

Cheers 👋

**Comment by LoremFooBar** [comment]
Appreciate it, thank you!
