### ISSUE TITLE
Rework icons

### ISSUE THREAD

**Issue by unlocomqx** [unlocomqx/intellij-virtual-kit#3]
I need help with this. If you can make better icons, please contribute. It would be greatly appreciated!

**Comment by wiverson** [comment]
Icons look fine to me. :)

Maybe use stuff from something like https://phosphoricons.com/ ?

**Comment by unlocomqx** [comment]
Hi @wiverson 👋 
I was thinking about icons to reflect a "sveltekit page" and "layout page" and so on

Current icons have inner shapes that are hard to discern at IDE icon size (imo)
![CleanShot 2024-02-02 at 20 37 30@2x](https://github.com/unlocomqx/intellij-virtual-kit/assets/793712/b15caf71-f0ef-47b7-a801-f65bb4cee047)

That's why I thought, there's definitely people better inspired than me to rework the icons and make them better suited for small sizes

Cheers

**Comment by wiverson** [comment]
Are all of the icons here? https://github.com/unlocomqx/intellij-virtual-kit/tree/main/src/main/resources/icons

**Comment by unlocomqx** [comment]
Yes, that's all of them

Btw, phosphor icons look really neat

**Comment by wiverson** [comment]
[new icons.zip](https://github.com/unlocomqx/intellij-virtual-kit/files/14144843/new.icons.zip)

Check these out

**Comment by unlocomqx** [comment]
Thank you very much
They look great

Just one thing, can you use the hard-drives icon for the server icon?

Thank you

**Comment by wiverson** [comment]
I switched from hard drive to cloud to sort of emphasize the "runs on the server" side. Figured the cloud was more universal for server.

FWIW I did a search for Phosphor for computer https://phosphoricons.com/?q=%22computer%22 ...and I kind of like the CPU or computer tower as well.

Here's all three plus a slightly tweaked cloud version

[server-alts.zip](https://github.com/unlocomqx/intellij-virtual-kit/files/14145070/server-alts.zip)

Maybe show to a few other folks and ask which one screams server lol

**Comment by wiverson** [comment]
Run a poll and get social media attention :)

**Comment by unlocomqx** [comment]
Thank you for the icons, they are just neat!

I will reach out to Twitter for opinions

Cheers

**Comment by unlocomqx** [comment]
It's now published!

Thank you @wiverson 

![CleanShot 2024-02-08 at 18 09 00@2x](https://github.com/unlocomqx/intellij-virtual-kit/assets/793712/bdddb142-48a8-476f-94bf-35c5e71cc216)
